 TEST_HISTO = [
    {
      "building_id": "Bldg-011635",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 50576.5,
      "latitude": -104.992,
      "longitude": 39.9181,
      "market": "Denver",
      "net_classification": "Type 2",
      "network_proximity": 1272.55,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80234",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "300 W 123rd Ave",
      "type": "Splice Point"
    },
    {
      "building_id": "Bldg-015170",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 63693.7,
      "latitude": -104.898,
      "longitude": 39.7177,
      "market": "Denver",
      "net_classification": "Type 2",
      "network_proximity": 1709.79,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80230",
      "profit": 0,
      "sites": [
        "Site-001282"
      ],
      "state": "CO",
      "street_address": "7901 E Lowry Blvd",
      "type": "Office - Multi Tenant"
    },
    {
      "building_id": "Bldg-015179",
      "city": "Englewood",
      "cpqs": [],
      "estimated_build_cost": 24685.4,
      "latitude": -104.856,
      "longitude": 39.5717,
      "market": "Denver",
      "net_classification": "Type 2",
      "network_proximity": 273.01,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80112",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "37 Inverness Dr E",
      "type": "Office - Multi Tenant"
    },
    {
      "building_id": "Bldg-015268",
      "city": "Englewood",
      "cpqs": [],
      "estimated_build_cost": 26547.1,
      "latitude": -104.903,
      "longitude": 39.6043,
      "market": "Denver",
      "net_classification": "Type 2",
      "network_proximity": 314.38,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80111",
      "profit": 0,
      "sites": [
        "Site-001402"
      ],
      "state": "CO",
      "street_address": "6200 S Quebec St",
      "type": "Office - Multi Tenant"
    },
    {
      "building_id": "Bldg-024054",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 35292.7,
      "latitude": -104.841,
      "longitude": 39.7754,
      "market": "Denver",
      "net_classification": "Type 2",
      "network_proximity": 763.09,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80239",
      "profit": 0,
      "sites": [
        "Site-002021"
      ],
      "state": "CO",
      "street_address": "12875 E 42nd Ave",
      "type": "Mobile Service Center"
    },
    {
      "building_id": "Bldg-029756",
      "city": "Golden",
      "cpqs": [],
      "estimated_build_cost": 13882.3,
      "latitude": -105.165,
      "longitude": 39.725,
      "market": "Denver",
      "net_classification": "Type 2",
      "network_proximity": 32.94,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80401",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "400 Indiana St",
      "type": "Hospital"
    },
    {
      "building_id": "Bldg-032121",
      "city": "Golden",
      "cpqs": [],
      "estimated_build_cost": 16495,
      "latitude": -105.189,
      "longitude": 39.7252,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 91,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80401",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "W 6th Ave & Interstate 70 Business",
      "type": "Splice Point"
    },
    {
      "building_id": "Bldg-032124",
      "city": "Aurora",
      "cpqs": [],
      "estimated_build_cost": 12402.7,
      "latitude": -104.83,
      "longitude": 39.7715,
      "market": "Denver",
      "net_classification": "Stubbed",
      "network_proximity": 0.06,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80011",
      "profit": 0,
      "sites": [
        "Site-002787",
        "Site-002788"
      ],
      "state": "CO",
      "street_address": "I-70 and Hwy 225",
      "type": "Splice Point"
    },
    {
      "building_id": "Bldg-037240",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 32628.7,
      "latitude": -105.021,
      "longitude": 39.7346,
      "market": "Denver",
      "net_classification": "Stubbed",
      "network_proximity": 674.29,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80204",
      "profit": 0,
      "sites": [
        "Site-002827"
      ],
      "state": "CO",
      "street_address": "Shoshone & 13th Ave",
      "type": "Splice Point"
    },
    {
      "building_id": "Bldg-038336",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 13030.9,
      "latitude": -105.013,
      "longitude": 39.7426,
      "market": "Denver",
      "net_classification": "Type 2",
      "network_proximity": 14.02,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80204",
      "profit": 0,
      "sites": [
        "Site-003999",
        "Site-004000"
      ],
      "state": "CO",
      "street_address": "318 Walnut St",
      "type": "Residential - Multi Tenant"
    },
    {
      "building_id": "Bldg-039595",
      "city": "Agate",
      "cpqs": [],
      "estimated_build_cost": 37921,
      "latitude": -103.941,
      "longitude": 39.4634,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 850.7,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80101",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "38619 Monroe St",
      "type": "Carrier POP"
    },
    {
      "building_id": "Bldg-040335",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 56802.4,
      "latitude": -104.97,
      "longitude": 39.7582,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 1480.08,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80205",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "13th & 225",
      "type": "Splice Point"
    },
    {
      "building_id": "Bldg-040336",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 56802.4,
      "latitude": -104.97,
      "longitude": 39.7582,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 1480.08,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80205",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "13th & Sherman",
      "type": "Splice Point"
    },
    {
      "building_id": "Bldg-058598",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 34631.4,
      "latitude": -104.989,
      "longitude": 39.7407,
      "market": "Denver",
      "net_classification": "Type 2",
      "network_proximity": 494.03,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80202",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "110 15th St",
      "type": "Conference/Convention Center"
    },
    {
      "building_id": "Bldg-059940",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 47378.8,
      "latitude": -104.957,
      "longitude": 39.7188,
      "market": "Denver",
      "net_classification": "Type 2",
      "network_proximity": 1165.96,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80206",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "151 Detroit St",
      "type": "Office - Multi Tenant"
    },
    {
      "building_id": "Bldg-066203",
      "city": "Englewood",
      "cpqs": [],
      "estimated_build_cost": 31970.9,
      "latitude": -104.871,
      "longitude": 39.5792,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 434.91,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80112",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "Inverness Main St",
      "type": "Office - Multi Tenant"
    },
    {
      "building_id": "Bldg-066517",
      "city": "Agate",
      "cpqs": [],
      "estimated_build_cost": 215556,
      "latitude": -103.955,
      "longitude": 39.4468,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 6771.87,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80101",
      "profit": 0,
      "sites": [
        "Site-004286"
      ],
      "state": "CO",
      "street_address": "39520 County Road 153",
      "type": "Cell Site"
    },
    {
      "building_id": "Bldg-068378",
      "city": "Englewood",
      "cpqs": [
        14700
      ],
      "estimated_build_cost": 25458.1,
      "latitude": -104.898,
      "longitude": 39.607,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 290.18,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80111",
      "profit": 18559.3,
      "sites": [
        "Site-004439"
      ],
      "state": "CO",
      "street_address": "5970 Greenwood Plaza Blvd",
      "type": "Office - Multi Tenant"
    },
    {
      "building_id": "Bldg-069509",
      "city": "Englewood",
      "cpqs": [],
      "estimated_build_cost": 15754.8,
      "latitude": -104.857,
      "longitude": 39.5836,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 74.55,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80112",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "7126 S Tucson Way",
      "type": "Office - Multi Tenant"
    },
    {
      "building_id": "Bldg-074834",
      "city": "Denver",
      "cpqs": [
        2970,
        2972,
        2973
      ],
      "estimated_build_cost": 15765.1,
      "latitude": -104.995,
      "longitude": 39.7511,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 74.78,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80202",
      "profit": 18459.7,
      "sites": [
        "Site-004364",
        "Site-004365"
      ],
      "state": "CO",
      "street_address": "1800 Larimer St",
      "type": "Office - Multi Tenant"
    },
    {
      "building_id": "Bldg-078149",
      "city": "Englewood",
      "cpqs": [],
      "estimated_build_cost": 33982.9,
      "latitude": -104.862,
      "longitude": 39.5771,
      "market": "Denver",
      "net_classification": "Type 2",
      "network_proximity": 719.43,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80112",
      "profit": 0,
      "sites": [
        "Site-004848"
      ],
      "state": "CO",
      "street_address": "88 Inverness Cir E",
      "type": "Office - Multi Tenant"
    },
    {
      "building_id": "Bldg-079533",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 27134.3,
      "latitude": -104.985,
      "longitude": 39.7546,
      "market": "Denver",
      "net_classification": "Stubbed",
      "network_proximity": 327.43,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80205",
      "profit": 0,
      "sites": [
        "Site-004903",
        "Site-004904"
      ],
      "state": "CO",
      "street_address": "2400 Curtis St",
      "type": "ILEC Central Office"
    },
    {
      "building_id": "Bldg-079573",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 13441.8,
      "latitude": -105.024,
      "longitude": 39.7622,
      "market": "Denver",
      "net_classification": "Stubbed",
      "network_proximity": 23.15,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80211",
      "profit": 0,
      "sites": [
        "Site-004905",
        "Site-004906",
        "Site-004907"
      ],
      "state": "CO",
      "street_address": "2929 W 32nd Ave",
      "type": "ILEC Central Office"
    },
    {
      "building_id": "Bldg-081122",
      "city": "Aurora",
      "cpqs": [],
      "estimated_build_cost": 33422.8,
      "latitude": -104.874,
      "longitude": 39.7383,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 700.76,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80010",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "1401 Emporia St",
      "type": "Cell Site"
    },
    {
      "building_id": "Bldg-081123",
      "city": "Aurora",
      "cpqs": [],
      "estimated_build_cost": 25854.1,
      "latitude": -104.801,
      "longitude": 39.7246,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 298.98,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80011",
      "profit": 0,
      "sites": [
        "Site-004929"
      ],
      "state": "CO",
      "street_address": "525 Laredo St",
      "type": "Cell Site"
    },
    {
      "building_id": "Bldg-081124",
      "city": "Aurora",
      "cpqs": [],
      "estimated_build_cost": 38372.2,
      "latitude": -104.721,
      "longitude": 39.7232,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 865.74,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80018",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "550 Valdai St",
      "type": "Cell Site"
    },
    {
      "building_id": "Bldg-081125",
      "city": "Aurora",
      "cpqs": [],
      "estimated_build_cost": 15193.2,
      "latitude": -104.828,
      "longitude": 39.6971,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 62.07,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80012",
      "profit": 0,
      "sites": [
        "Site-004930"
      ],
      "state": "CO",
      "street_address": "13801 E Mississippi Ave",
      "type": "Cell Site"
    },
    {
      "building_id": "Bldg-081126",
      "city": "Aurora",
      "cpqs": [],
      "estimated_build_cost": 40656.7,
      "latitude": -104.824,
      "longitude": 39.7129,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 941.89,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80012",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "14125 E Cedar Ave",
      "type": "Cell Site"
    },
    {
      "building_id": "Bldg-081131",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 17914.3,
      "latitude": -104.978,
      "longitude": 39.7382,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 122.54,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80202",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "750 14th St",
      "type": "Cell Site"
    },
    {
      "building_id": "Bldg-081132",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 30258.7,
      "latitude": -104.983,
      "longitude": 39.735,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 396.86,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80203",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "1196 Grant St",
      "type": "Cell Site"
    },
    {
      "building_id": "Bldg-081143",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 37600,
      "latitude": -104.995,
      "longitude": 39.7346,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 840,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80204",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "1170 Galapago St",
      "type": "Cell Site"
    },
    {
      "building_id": "Bldg-081144",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 16929.7,
      "latitude": -105.028,
      "longitude": 39.7386,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 100.66,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80204",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "3168 W 14th Ave",
      "type": "Cell Site"
    },
    {
      "building_id": "Bldg-081146",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 37962.1,
      "latitude": -104.998,
      "longitude": 39.7255,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 852.07,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80204",
      "profit": 0,
      "sites": [],
      "state": "CO",
      "street_address": "570 Santa Fe Dr",
      "type": "Cell Site"
    },
    {
      "building_id": "Bldg-081147",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 23382.2,
      "latitude": -104.848,
      "longitude": 39.779,
      "market": "Denver",
      "net_classification": "Fiber Only",
      "network_proximity": 244.05,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80239",
      "profit": 0,
      "sites": [
        "Site-004957"
      ],
      "state": "CO",
      "street_address": "12075 E 45th Ave",
      "type": "Cell Site"
    },
    {
      "building_id": "Bldg-081150",
      "city": "Denver",
      "cpqs": [],
      "estimated_build_cost": 20764.2,
      "latitude": -104.939,
      "longitude": 39.6779,
      "market": "Denver",
      "net_classification": "Stubbed",
      "network_proximity": 185.87,
      "on_zayo_network_status": "Not on Zayo Network",
      "postal_code": "80222",
      "profit": 0,
      "sites": [
        "Site-004964",
        "Site-004965"
      ],
      "state": "CO",
      "street_address": "4120 E Evans Ave",
      "type": "Cell Site"
    }]